{{- if .Values.secrets.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.google_maps.existingSecret }}
  labels:
    app: {{ template "market-web.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
type: Opaque
data:
  key: {{ .Values.google_maps.access_key | toString | b64enc }}
{{- end -}}
