# Default values for market.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
#
replicaCount: 1
#
image:
  repository: us.gcr.io/responsive-edge-344815/market
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""
  digest: "sha256:b7e5d51703aa1249fa31cf208d979d242fa7ca04aba817fb9f617edd3d693827"
#
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
#
kratos_url: "http://galoy-kratos-public"
#
upload:
  max_filesize: 30822400
  limit: 20
#
secrets:
  create: true
#
jwt:
  existingSecret: market-jwt
  secretKey: key
  issuer: PuraVida
  audience: PuraVida
  key: CHANGE-ME-I-AM-INSECURE
  lifetime: 2d
  algorithm: HS512
#
mongodb:
  auth:
    existingSecret: market-mongo
    secretHostKey: dsn
    dsn: DATA-SOURCE-NAME
#
## Details for google cloud storage
gcs:
  existingSecret: market-gcs
  project_id: "your-project-id"
  bucket_name: "bucket-name"
  service_account:
    name: "sa-email"
    key: "sa-private-key"
#
google_maps:
  existingSecret: market-maps
  access_key: "google_maps_access_key"
#
hash:
  salt_rounds: 10
  pepper: "this is for testing"
#
serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""
#
podAnnotations: {}
#
podSecurityContext: {}
# fsGroup: 2000
#
securityContext:
# capabilities:
#   drop:
#   - ALL
# readOnlyRootFilesystem: true
# runAsNonRoot: true
# runAsUser: 1000
#
service:
  type: ClusterIP
  port: 3000
#
ingress:
  enabled: false
  className: ""
  annotations:
  nginx.ingress.kubernetes.io/proxy-body-size: 25m
  # kubernetes.io/ingress.class: nginx
  # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local
#
resources: {}
# We usually recommend not to specify default resources and to leave this as a conscious
# choice for the user. This also increases chances charts run on environments with little
# resources, such as Minikube. If you do want to specify resources, uncomment the following
# lines, adjust them as necessary, and remove the curly braces after 'resources:'.
# limits:
#   cpu: 100m
#   memory: 128Mi
# requests:
#   cpu: 100m
#   memory: 128Mi
#
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80
#
nodeSelector: {}
#
tolerations: []
#
affinity: {}
