apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "market.fullname" . }}
  labels:
    app: {{ template "market.fullname" . }}
    {{- include "market.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "market.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "market.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "market.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          {{- if .Values.image.tag }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          {{- else if .Values.image.digest }}
          image: "{{ .Values.image.repository }}@{{ .Values.image.digest }}"
          {{- else }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          {{- end }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /graphql
              port: http
          readinessProbe:
            httpGet:
              path: /graphql
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: PORT
              value: {{ .Values.service.port | quote }}
            - name: THROTTLE_TTL
              value: {{ 6 | quote }}
            - name: THROTTLE_LIMIT
              value: {{ 1 | quote }}
            - name: DATABASE_HOST
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.mongodb.auth.existingSecret }}
                  key: {{ .Values.mongodb.auth.secretHostKey }}
            - name: GCP_PROJECT_ID
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.gcs.existingSecret }}
                  key: project_id
            - name: GCP_BUCKET_NAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.gcs.existingSecret }}
                  key: bucket_name
            - name: GCP_CLIENT_EMAIL
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.gcs.existingSecret }}
                  key: service_account
            - name: GCP_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.gcs.existingSecret }}
                  key: service_account_key
            - name: GOOGLE_MAPS_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.google_maps.existingSecret }}
                  key: key
            - name: JWT_ISSUER
              value: {{ .Values.jwt.issuer }}
            - name: JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.jwt.existingSecret }}
                  key: {{ .Values.jwt.secretKey }}
            - name: JWT_LIFE_TIME
              value: {{ .Values.jwt.lifetime }}
            - name: JWT_ALGORITHM
              value: {{ .Values.jwt.algorithm }}
            - name: UPLOAD_FILE_MAX_FILE_SIZE
              value: {{ .Values.upload.max_filesize | quote }}
            - name: UPLOAD_FILE_MAX_FILE_NUMBER
              value: {{ .Values.upload.limit | quote }}
            - name: HASH_SALT_ROUNDS
              value: {{ .Values.hash.salt_rounds | quote }}
            - name: HASH_PEPPER
              value: {{ .Values.hash.pepper }}
            - name: KRATOS_PUBLIC_ENDPOINT
              value: {{ .Values.kratos_url }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
