{{- if .Values.secrets.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.mongodb.auth.existingSecret }}
  labels:
    app: {{ template "market.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    app.kubernetes.io/component: mongodb
type: Opaque
data:
  {{ .Values.mongodb.auth.secretHostKey }}: {{ .Values.mongodb.auth.dsn | toString | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.jwt.existingSecret }}
  labels:
    app: {{ template "market.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
type: Opaque
data:
  {{ .Values.jwt.secretKey }}: {{ .Values.jwt.key | toString | b64enc }}
{{- end -}}
