{{- if .Values.secrets.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.mongodb.auth.existingSecret }}
  labels:
    app: {{ template "market.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    app.kubernetes.io/component: mongodb
type: Opaque
data:
  {{ .Values.mongodb.auth.secretHostKey }}: {{ .Values.mongodb.auth.dsn | toString | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.jwt.existingSecret }}
  labels:
    app: {{ template "market.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
type: Opaque
data:
  {{ .Values.jwt.secretKey }}: {{ .Values.jwt.key | toString | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.gcs.existingSecret }}
  labels:
    app: {{ template "market.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
type: Opaque
data:
  project_id: {{ .Values.gcs.project_id | toString | b64enc }}
  bucket_name: {{ .Values.gcs.bucket_name | toString | b64enc }}
  service_account: {{ .Values.gcs.service_account.name | toString | b64enc }}
  service_account_key: {{ .Values.gcs.service_account.key | toString | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.google_maps.existingSecret }}
  labels:
    app: {{ template "market.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
type: Opaque
data:
  key: {{ .Values.google_maps.access_key | toString | b64enc }}
{{- end -}}
